<?php require('template/header.phtml') ?>
<?php require ('controllers/users.php')?>


    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>UserId</th><th>Username</th><th>Password</th>
            </tr>
            </thead>
            <tbody>

            <?php



            //foreach ($view->AuctionDataSet as $AuctionData){
                //echo '<tr> <td>' .AuctionData,getUserId();
            //}



            //echo getDatSetAndSqlQuery();
            ?>
            </tbody>
        </table>
    </form>

<?php require('template/footer.phtml') ?>