<?php
require('template/header.phtml');
//require ('../controllers/users.php');
require ('../controllers/users.php');
?>




    <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
        <table class="table table-hover">
            <thead>
            <tr>
                <th>UserId</th><th>Username</th><th>Password</th>
            </tr>
            </thead>
            <tbody>

            <?php

            foreach ($AuctionDataSet1 as $Key => $AuctionData){
                echo '<tr> <td>' . $AuctionData->getUserId() . '</td> <td>' . $AuctionData->getUsername() . '</td> <td>' . $AuctionData->getPassword();
            }
            ?>
            </tbody>
        </table>
    </form>

<?php require('../template/footer.phtml') ?>